# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

permissions:
  id-token: write
  contents: write
  packages: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: ./build.sh

    - name: GHCR login
      uses: docker/login-action@v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push app container image
      id: push
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        file: Dockerfile
        push: true
        load: true
        tags: ghcr.io/${{ github.repository_owner }}/epss-golang-demo:latest

    - name: generate build provenance for app
      uses: github-early-access/generate-build-provenance@main
      with:
        subject-path: '${{ github.workspace }}/app'

    - name: generate build provenance for app's container image
      uses: github-early-access/generate-build-provenance@main
      with:
        subject-name: ghcr.io/${{ github.repository_owner }}/epss-golang-demo
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true

    - name: Scan image with Anchore
      id: anchorescan
      uses: anchore/scan-action@v3
      with:
        image: ghcr.io/${{ github.repository_owner }}/epss-golang-demo:latest
        output-format: sarif #should be the default (setting explicitly anyways)

    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.anchorescan.outputs.sarif }}

    - name: Inspect action SARIF report
      run: cat ${{ steps.anchorescan.outputs.sarif }}
